config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'games#index'

  resources :games do
    resources :reviews
  end
  resources :votes, only: [:create]



  namespace :admin do
    resources :users, except: [:new, :edit, :update]
    resources :games, except: [:new, :edit, :update]
    resources :reviews, except: [:new, :edit, :update]
    resources :home, only: [:index]
  end

  namespace :api do
    namespace :v1 do
      resources :votes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :reviews
  has_many :users, through: :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user, optional: true
  belongs_to :game

  has_many :users
  has_many :votes

  validates_presence_of :user

  def vote_total
    total = 0
    votes.each do |vote|
      total += vote.value
    end
    total
  end
end

app/models/user.rb
  class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :games, through: :reviews
  has_many :votes


  def is_admin?
    role == 'admin'
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :review

end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  before_filter :authorize_admin!
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to admin_games_path,
    notice: 'Game was successfully deleted'
  end

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  before_filter :authorize_admin!
  def index
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_filter :authorize_admin!
  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to admin_reviews_path,
    notice: 'Review was successfully deleted'
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authorize_admin!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path,
    notice: 'User was successfully deleted'
  end

end

app/controllers/api/v1/votes_controller.rb
class Api::V1::VotesController < ApplicationController
  protect_from_forgery with: :null_session

  def create

    @review = Review.find(vote_params[:review_id])
    @game = @review.game
    @vote = Vote.find_by(user_id: current_user.id, review_id: @review.id)
    user_input = vote_params[:value].to_i

    if @vote
      if @vote.value == 0
        @vote.value = user_input
        @vote.save
        render_json("Your vote has been updated!")
      else
        if @vote.value == user_input
          render_json("You can only vote once!")
        else
          @vote.value = 0
          @vote.save
          render_json("Your vote has been updated!")
        end
      end
    else
      @vote = Vote.create(user_id: current_user.id, review_id: vote_params[:review_id], value: vote_params[:value])
      render_json("Thanks for your vote!")
    end
  end

  private

  def vote_params
    params.require(:vote).permit(:review_id, :value)
  end

  def render_json(message)
    render json: {
      voteTotal: @review.vote_total,
      voteMessage: message,
      reviewID: @review.id
    }, status: :created
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def authorize_admin!
    if current_user.nil? or !current_user.is_admin?
      flash[:notice] = "You are not authorized to view this resource."
      redirect_to root_path
    end
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_action :set_game,
  only: [:show, :edit, :update, :destroy]


  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    @reviews = @game.reviews
  end

  def new
    if user_signed_in?
      @game = Game.new
    end
  end

  def create
    if user_signed_in?
      @game = Game.new(game_params)
      if @game.save
        flash[:notice] = "New Game added"
        redirect_to games_path
      else
        flash[:alert] = "Game not added, please fix"
        render :new
      end
    end
  end

  def update
    if user_signed_in?
      if @game.update(game_params)
        redirect_to @game,
          notice: 'Game was successfully updated'
      else
        render :edit
      end
    end
  end

  def destroy
    if user_signed_in?
      @game.destroy
      redirect_to games_url,
        notice: 'Game was successfully deleted'
    end
  end

  private

  def set_game
      @game = Game.find(params[:id])
    end

  def game_params
    params.require(:game).permit(
      :name,
      :developer,
      :genre,
      :comments,
      :user_id
    )
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def show
    @game = Game.find(params[:game_id])
    @review = Review.find(params[:id])
  end

  def new
    if user_signed_in?
      @game = Game.find(params[:game_id])
      @review = Review.new
    end
  end

  def create
    if user_signed_in?

      @game = Game.find(params[:game_id])
      @review = Review.new(review_params)

      @review.game = @game

      if @review.save
        flash[:notice] = "New Review added"
        redirect_to @game
      else
        flash[:alert] = "Review not added, please fix"
        render :new
      end
    end
  end

  def edit
    @game = Game.find(params[:game_id])
    @review = Review.find(params[:id])
  end

  def update
    @game = Game.find(params[:game_id])
    @review = Review.find(params[:id])

    if user_signed_in?
      if @review.update_attributes(review_params)
        flash[:notice] = "Review updated"
        redirect_to game_path(@game)
      else
        flash[:alert] = "Review not updated, please fix"
        render :edit
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])

    if user_signed_in?
      @review.destroy
      flash[:notice] = "Review was deleted"
      redirect_to game_path(params[:game_id])
    end
  end

  private

  def review_params
    params.require(:review).permit(
      :title,
      :body,
      :user_id,
      :username
    )
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController


  def create
    if user_signed_in?

        @review = Review.find(vote_params[:review_id])
        @game = @review.game
        @vote = Vote.find_by(user_id: current_user.id, review_id: @review.id)
        user_input = vote_params[:value].to_i

        if @vote
          if @vote.value == 0

          @vote.value = user_input
          @vote.save
          flash[:alert] = "Your vote has been updated!"
          redirect_to @game
        else
          if @vote.value == user_input

            flash[:error] = "You can only vote once!"
            redirect_to @game
          else
            @vote.value = 0
            @vote.save

            flash[:alert] = "Your vote has been updated!"
            redirect_to @game
          end
        end
      else
        @vote = Vote.create(vote_params)

        flash[:alert] = "Thanks for your vote!"
        redirect_to @game
      end
    end

    private

    def vote
      @vote ||= Vote.find_by(user_id: vote[:user_id], review_id: vote[:review_id])
    end

    def vote_params
      params.require(:vote).permit(:user_id, :review_id, :value)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/games/index.html.erb
<h1>Master List of Games</h1>
  <ul>
    <% @games.each do |game| %>
      <li><%= link_to game.name, admin_game_path(game) %></li>
    <% end %>
  </ul>

<%= link_to 'Back to Control Panel', admin_home_index_path %>

app/views/admin/games/show.html.erb
<h3><%= @game.name %></h3>
  <hr>
  <h4>Developer: <%= @game.developer %></h4>
  <h4>Genre: <%= @game.genre %></h4>
  <h4>Game created: <%= @game.created_at %></h4>
  <hr>
  <%= button_to 'Return to Index', :back, class: "button", :method => :get %>
  <%= button_to 'Delete Game', admin_game_path(@game), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/admin/home/index.html.erb
<h1>Admin Control Panel</h1>
<hr>
<li><%= link_to "Users Master List", admin_users_path %></li>
<li><%= link_to "Games Master List", admin_games_path %></li>
<li><%= link_to "Reviews Master List", admin_reviews_path %></li>

<hr>

app/views/admin/reviews/index.html.erb
<h1>Master List of Reviews</h1>

  <% @reviews.each do |review| %>
  <ul>
      <strong><%= review.game.name %></strong>
      <li><%= link_to review.title, admin_review_path(review) %></li>
    </ul>
    <% end %>

<hr>

<%= link_to 'Back to Control Panel', admin_home_index_path %>

app/views/admin/reviews/show.html.erb
<h3><%= @review.title %></h3>

  <h4>Author: <%= @review.username %></h4>
  <h4>body: <%= @review.body %></h4>
  <h4>Review created: <%= @review.created_at %></h4>
  <hr>
  <%= button_to 'Return to Index', :back, class: "button", :method => :get %>
  <%= button_to 'Delete Review', admin_review_path(@review), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/admin/users/index.html.erb
<h1>Master List of Users</h1>
  <ul>
    <% @users.each do |user| %>
      <li><%= link_to user.username, admin_user_path(user) %></li>
    <% end %>
  </ul>

  <%= link_to 'Back to Control Panel', admin_home_index_path %>

app/views/admin/users/show.html.erb
<h3><%= @user.username %></h3>
  <hr>
  <h4>Current Role: <%= @user.role %></h4>
  <h4>Last active login: <%= @user.last_sign_in_at %></h4>
  <h4>Account created: <%= @user.created_at %></h4>
  <hr>
  <%= button_to 'Return to Index', :back, class: "button", :method => :get %>
  <%= button_to 'Delete User', admin_user_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/games/_form.html.erb
<%= form_for (@game) do |f| %>

    <div class = "field">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name %>
    </div>

    <div class = "field">
      <%= f.label :developer %>
      <%= f.text_field :developer %>
    </div>

    <div class = "field">
      <%= f.label :genre %>
      <%= f.text_field :genre %>
    </div>

    <div class = "field">
      <%= f.label :comments %>
      <%= f.text_field :comments %>
    </div>

    <div>
      <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>



    <div class = "actions">
      <%= f.submit ("Add game") %>
    </div>


  <% end %>

app/views/games/edit.html.erb
<h1> Edit <%= @game.name %></h1>

<%= render 'form' %>

<%= link_to 'View Game', game_path %>
|
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Games</h1>
<% if user_signed_in? %>
  <%= link_to "Add a New Game", new_game_path %>
<% end %>
<hr>
<% @games.each do |game| %>
  <h2><%= link_to game.name, game_path(game) %></h2>
  <ul>
    <li>Developer: <%= game.developer %></li>
    <li>Genre: <%= game.genre %></li>
  </ul>
<hr>
<% end %>

app/views/games/new.html.erb
<h1>Add a New Game</h1>

<%= render 'form' %>

app/views/games/show.html.erb
<h1> <%= @game.name %></h1>
<% if current_user && current_user.is_admin? || current_user.id == @game.user_id %>
  <h5><%= link_to 'Edit', edit_game_path(@game) %>
  | <%= link_to 'Delete Game', @game, method: :delete, data: { confirm: 'Are you sure?' } %></h5>
<% end %>

<h5><%= link_to 'Back', games_path %></h5>

    <ul>
      <li>Developer: <%= @game.developer %></li>
      <li>Genre: <%= @game.genre %></li>
      <li>Comments: <%= @game.comments %></li>
    </ul>
<hr>
<h2><Strong>What the people are thinking:</strong></h2>
    <% if user_signed_in? %>
      <h5><%= link_to "Add a Review", new_game_review_path(@game) %></h5>
    <% end %>

    <% @reviews.each do |review| %>
      <h3><strong><%= review.title %></strong></h3>
      <h5>Reviewed by: <%= review.username %></h5>
      <%= review.body %>


    <h5><strong><span class="vote-total" >Vote Ranking:
      <span id="vote-total-<%= review.id %>" >
        <% if review.vote_total %>
          <%= review.vote_total %>
        <% else %>
          0
        <% end %>
      </span>
    </span></strong></h5>

    <% if user_signed_in? %>
    <div id="voting-buttons">
      <%= button_to "+", votes_path(Vote.new, params: { vote: { user_id: current_user.id, review_id: review.id, value: 1 } }), method: :post, id: "upvote-#{review.id}", class: "upvote" %>
      <%= button_to "-", votes_path(Vote.new, params: { vote: { user_id: current_user.id, review_id: review.id, value: -1 } }), method: :post, id: "downvote-#{review.id}", class: "downvote" %>
    </div>
  <% end %>

    <% if !user_signed_in? %>
      (<%= link_to "Sign in to vote!", new_user_session_path %>)
    <% end %>
  </div>


      <% if current_user && current_user.is_admin? || current_user.id == review.user_id %>
        <h5><%= link_to "Wanna change your review for: #{@game.name}?", game_review_path(@game, review) %></h5>
      <% end %>
<hr>
    <% end %>

app/views/layouts/_navigation.html.erb
<% if user_signed_in? %>
  signed in as <strong><%= current_user.username %></strong>
  <br /><%= link_to :sign_out, destroy_user_session_path, method: :delete %>
  | <%= link_to 'edit info', edit_user_registration_path %>
    <% if current_user && current_user.is_admin? %>
         | <strong><%= link_to 'Admin tools', admin_home_index_path %></strong>
    <% end %>

<% else %>
  <%= link_to :sign_in, new_user_session_path %>
  | <%= link_to 'Sign up', new_user_registration_path %>
<% end %>
<h5><%= link_to 'Home', games_path %></h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoGameReviewSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for [@game, @review] do |f| %>

<% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
        <ul>
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class = "field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class = "field">
      <%= f.label :body %>
      <%= f.text_field :body %>
    </div>

    <div>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :username, :value => current_user.username %>
    </div>


    <div class = "actions">
      <%= f.submit ("Add review") %>
    </div>


  <% end %>

app/views/reviews/edit.html.erb
<h1> Edit your review</h1>

<%= form_for [@game, @review] do |f| %>

<% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
        <ul>
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class = "field">
      <%= f.label :title, 'Edit Title' %>
      <%= f.text_field :title, :value => @review.title %>
    </div>

    <div class = "field">
      <%= f.label :body, 'Edit Body' %>
      <%= f.text_field :body, :value => @review.body %>
    </div>

    <div class = "actions">
      <%= f.submit ("Submit Changes") %>
    </div>

    <h5><%= link_to "Changed your mind?", game_review_path(@game, @review) %></h5>



  <% end %>

app/views/reviews/new.html.erb
<%= form_for [@game, @review] do |f| %>

<% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
        <ul>
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class = "field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class = "field">
      <%= f.label :body %>
      <%= f.text_field :body %>
    </div>

    <div>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :username, :value => current_user.username %>
    </div>


    <div class = "actions">
      <%= f.submit ("Add review") %>
    </div>


  <% end %>

app/views/reviews/show.html.erb
  <p><strong><%= @review.title %></strong>
  <br />Reviewed by: <%= @review.username %>
  <ul>
    <li><%= @review.body %></li>
  </ul>


  <% if current_user && current_user.is_admin? || current_user.id == @review.user_id %>
      <br /><%= link_to 'Edit', edit_game_review_path(@game, @review) %>
      | <%= link_to 'Delete Review', game_review_path(@game, @review), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>

    <p><%= link_to 'Back', games_path %></p>